name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build Linux-amd64
      run: env GOOS=linux GOARCH=amd64 go build -v

    - name: Upload Linux-amd64 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Linux-amd64
        path: |
          ./erupe-ce
          ./config.json
          ./www/
          ./savedata/
          ./bin/
          ./RoadShopItems.csv
          ./.dockerignore
          ./Dockerfile
          ./docker-compose.yml
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          # Artifact name
          name: Linux-amd64
      - name: Display structure of downloaded files
        run: ls -R
      - name: Move Artifact files
        run: mv ./ ./published
      - name: Docker Build Tag Publish
        # You may pin to the exact commit or the version.
        # uses: bitovi/github-actions-docker-publish@8db2834ce66baa4d849c7d87df3f47118233c993
        uses: bitovi/github-actions-docker-publish@v1.0.2
        with:
          checkout: false
          image_tag: vladoms/mhfz:latest
          docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Display structure of downloaded files
        run: ls -R
