name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build Tag Publish
        uses: bitovi/github-actions-docker-publish@v1.0.2
        with:
          checkout: false
          image_tag: vladoms/mhfz:latest
          docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_password: ${{ secrets.DOCKERHUB_TOKEN }}

