name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: vladoms/mhfz:latest, vladoms/mhfz:9.0.0.1