name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build Tag Publish
        uses: bitovi/github-actions-docker-publish@v1.0.2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: vladoms/mhfz:latest
          context: ./published
          file: ./published/Dockerfile
          
          
      - name: Display structure of downloaded files
        run: ls -R
